
channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  - pip:
    - rpaframework==28.5.1
    - robocorp==2.0.2
    - pandas==2.2.2
    - robocorp-browser==2.3.3
    - beautifulsoup4 
    - robotframework-browser==18.4.0
    - gspread 
    - oauth2
    - googleapi 
    - openai== 1.25.1
    - python-wordpress-xmlrpc
    - keyboard
    - httplib2
    - gspread-formatting

rccPostInstall:
  - rfbrowser init